version: '3.8'
services:
  # Le stockage des images (le coeur)
  registry:
    image: registry:2
    container_name: harbor-registry
    restart: always
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_SECRET: devsecops-secret

  # L'interface visuelle (pour voir tes images dans le navigateur)
  registry-ui:
    image: joxit/docker-registry-ui:static
    container_name: harbor-ui
    restart: always
    ports:
      - "8181:80"
    environment:
      - REGISTRY_TITLE=Mon_Harbor_Marketplace
      - REGISTRY_URL=http://100.115.122.20:5000
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
