---
- name: Déployer l'application Marketplace en Production
  hosts: prod
  vars:
    projet_dest: /opt/marketplace
    # Plus besoin de registry_url, Docker Hub est le défaut.
  
  tasks:
    - name: Créer le répertoire de destination
      file:
        path: "{{ projet_dest }}"
        state: directory
        mode: '0755'

    - name: Copier le fichier docker-compose de production
      copy:
        src: ../marketplace/docker-compose.yml
        dest: "{{ projet_dest }}/docker-compose.yml"

    - name: Créer le fichier .env pour Docker Compose
      copy:
        dest: "{{ projet_dest }}/.env"
        content: |
          DB_USER=root
          DB_PASSWORD=root
          DB_NAME=marketplace
          MAIL_USER=sushibaka36@gmail.com
          MAIL_PASSWORD=tgkmyjjrczvzghjm

    - name: Sanitize Docker Config (User & Root)
      shell: "mkdir -p ~/.docker && echo '{}' > ~/.docker/config.json"

    - name: Ensure /root/.docker is clean
      shell: "mkdir -p /root/.docker && echo '{}' > /root/.docker/config.json"
      become: yes
      ignore_errors: yes

    - name: Démarrer ou mettre à jour la stack de production (App + MySQL)
      shell: |
        export DOCKER_CONFIG=/tmp/docker_deploy_config
        mkdir -p $DOCKER_CONFIG
        echo "{{ docker_pass }}" | docker --config $DOCKER_CONFIG login -u "{{ docker_user }}" --password-stdin
        docker --config $DOCKER_CONFIG compose up -d --pull always
        rm -rf $DOCKER_CONFIG
      args:
        chdir: "{{ projet_dest }}"

    - name: Vérifier que l'application est bien en ligne (Port 8082)
      wait_for:
        port: 8082
        delay: 15
        timeout: 120
        msg: "L'application Marketplace n'est pas accessible sur le port 8082."
