[outils]
serveur_outils ansible_host=100.115.122.20 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[prod]
serveur_prod ansible_host=100.115.122.20 ansible_user=root ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
