---
- name: Installer Docker et configurer les outils DevSecOps (SonarQube et Harbor)
  hosts: outils
  vars:
    projet_dest: /opt/devsecops
  tasks:
    - name: Ajouter la clé GPG de Trivy
      apt_key:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        state: present

    - name: Ajouter le dépôt Trivy
      apt_repository:
        repo: "deb https://aquasecurity.github.io/trivy-repo/deb {{ ansible_distribution_release }} main"
        state: present

    - name: Installer les dépendances
      apt:
        name: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release, python3-pip, python3-docker, openjdk-17-jdk, trivy]
        state: present
        update_cache: yes

    - name: Ajouter la clé GPG officielle de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Configurer le dépôt Docker
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Installer Docker Engine
      apt:
        name: [docker-ce, docker-ce-cli, containerd.io, docker-compose-plugin]
        state: present

    - name: Démarrer Docker (Compatibilité WSL2)
      service:
        name: docker
        state: started
        enabled: yes
      ignore_errors: yes

    # ATTENTION: vm.max_map_count au moins égal à 262144 est exigé par Elasticsearch embarqué dans SonarQube
    - name: Configurer vm.max_map_count (pour SonarQube)
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes
      ignore_errors: yes

    - name: Lancer SonarQube
      command: docker compose up -d
      args:
        chdir: "{{ projet_dest }}/serveurs/sonarqube"

  handlers:
    - name: Redémarrer Docker
      service:
        name: docker
        state: restarted
